### ISSUE TITLE
First example

### ISSUE THREAD

**Issue by mentat51** [firodj/ffmpeg-cffi-py#1]
Hello.
I'm trying to pythonify the first C tutorial to use ffmpef-cffi-py, but it doesn't work.
I'm new to cffi and don't understand where is the problem.
Traceback (most recent call last):
  File "tutorial01.py", line 156, in <module>
    main()
  File "tutorial01.py", line 47, in main
    if avformat.avformat_open_input(ffi.addressof(pFormatCtx), sys.argv[1],
  File "C:\usr\bin\Python35\lib\site-packages\cffi\api.py", line 454, in addressof
    raise TypeError("addressof(pointer)")
TypeError: addressof(pointer)

If you can help me, I will try to make all the tutorial using pysdl2 for a full video player.

Thanks in advance.

[tutorial01.zip](https://github.com/firodj/ffmpeg-cffi-py/files/163970/tutorial01.zip)

[tutorial01_c.zip](https://github.com/firodj/ffmpeg-cffi-py/files/163982/tutorial01_c.zip)

**Comment by senyai** [comment]
`AVFormatContext * *` works for me:

```
# Open video file
pFormatCtx = ffi.new('AVFormatContext * *')
if avformat.avformat_open_input(pFormatCtx, sys.argv[1],
                                ffi.NULL, ffi.NULL)!=0:
    return -1 # Couldn't open file
```

as in your `c` example. Then `formatCtx = pFormatCtx[0]`. You don't create `AVFormatContext`, only pointer. Yes, `ffi.new('AVFormatContext *')` creates object itselt `<cdata 'AVFormatContext *' owning 1344 bytes>`. 01:30 am here, hope you understand me anyway.

**Comment by senyai** [comment]
I wrote an example that saves frames from a movie and uses `ffmpeg-cffi-py` module itself

``` python
    from ffmpeg import register_all
    from ffmpeg.formatctx import InputFormat


    def main():
        register_all()
        format_context = InputFormat.open(r"GOPR9001.MP4")
        format_context.audio_stream = None
        format_context.open_decoder()
        for idx, frame in enumerate(format_context.next_frame()):
            img = frame.process()
            print idx
            img.save('{}.png'.format(idx))


    if __name__ == '__main__':
        main()
```

**Comment by senyai** [comment]
Also note, that `avpicture_get_size` is deprecated.
